version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      timezone: 'America/New_York'
    rebase-strategy: 'disabled'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      timezone: 'America/New_York'
    rebase-strategy: 'disabled'
